CMAKE_MINIMUM_REQUIRED(VERSION 3.16 FATAL_ERROR)

# SET PROJECT NAME
PROJECT(map-viewer)

# SET LANGUAGE STANDARD
SET(CMAKE_CXX_STANDARD 17)
SET(CMAKE_CXX_STANDARD_REQUIRED ON)

# CUSTOM EXTERNAL DEPENDENCIES
SET(CUSTOM_CONFIG_PATH ${CMAKE_SOURCE_DIR}/cmake/config)
SET(CMAKE_PREFIX_PATH ${CUSTOM_CONFIG_PATH} ${CMAKE_PREFIX_PATH})
FIND_PACKAGE(imgui REQUIRED)

# MANAGED EXTERNAL DEPENDENCIES (VCPKG)
FIND_PACKAGE(SDL3 CONFIG REQUIRED)
FIND_PACKAGE(glm CONFIG REQUIRED)
FIND_PACKAGE(glad CONFIG REQUIRED)
FIND_PACKAGE(OpenGL REQUIRED)
FIND_PACKAGE(GDAL CONFIG REQUIRED)
FIND_PACKAGE(GEOS CONFIG REQUIRED)
FIND_PACKAGE(SQLite3 REQUIRED)
FIND_PACKAGE(stb REQUIRED)


ADD_SUBDIRECTORY(core)

# CREATE EXECUTABLE
ADD_EXECUTABLE(main src/main.cpp)

# INCLUDE LIBRARIES IN TARGET
TARGET_LINK_LIBRARIES(main PRIVATE core)

# COPY DATA/ASSETS FOLDER TO BUILD DIRECTORY
FILE(COPY ${CMAKE_SOURCE_DIR}/assets DESTINATION ${CMAKE_BINARY_DIR})
FILE(COPY ${CMAKE_SOURCE_DIR}/data DESTINATION ${CMAKE_BINARY_DIR})